### ISSUE TITLE
Revise use of HTML entities for real UTF-8

### ISSUE THREAD

**Issue by gizmecano** [gizmecano/opencart-3-fr#63]
In some cases (_e.g._ window popup), HTML entities are not properly rendering but displayed as full code (_e.g._ `&#160;`). Therefore, it seems preferable to harmonize the use of these special characters by using the UTF-8 encoding only (contrary to what was considered in #53).

  - [x] `&#38;` (only in full version files)
  - [x] `&#160;` replace by [`U+2009`](https://unicode-table.com/en/2009/) (988ddc7adba6172b2780a45ee87c01dfdcaae35a and 4ef00fa903f46e8ac4e6224e260ba1e49228d811)
  - [x] `&#8226;` (only in full version files)
