### ISSUE TITLE
Review changes in OpenCart release (3.0.3.0)

### ISSUE THREAD

**Issue by gizmecano** [gizmecano/opencart-3-fr#67]
Review changes that have appeared in a stable version of OpenCart (3.0.3.0) and create the correlated tasks for the language pack.

- [x] update clone repository to [version 3.0.3.0](https://github.com/gizmecano/opencart/releases/tag/3.0.3.0)

---

## Major changes

- [x] `<admin\extension\advertise>`  #68 
- [x] `<catalog\extension\advertise>` #75 

## Minor changes

- [x] `<admin\extension\shipping>` and `<catalog\extension\shipping>` #69 
- [x] `<admin\extension\extension>` #70 

## Other patches

- [x] `<admin\extension\extension>` #71 
- [x] `<admin\extension\module>` #72 
- [x] `<admin\extension\openbay>` #73 
- [x] `<admin\extension\payment>` #74 
- [x] `<catalog\extension\payment>` #76
